### ISSUE TITLE
To-do list: Repo/Website documentation for developers

### ISSUE THREAD

**Issue by GabrielPelletier** [OpenScienceOfficeHours/osoh_website#15]
**Decisions to make**
All documentation goes in the README file? Other documentation file needed? Does it all fit in the README? What should go in the README and what goes in extra docs?

The idea is that someone without much programming/website design knowledge would be able to make simple edits to the website, which are needed on a regular basis.

**Check list of elements needed**
- [ ] General description of website structure and of how the front-end elements map onto the back-end.
- [ ] Step-by-step guide for Monthly update (Month Theme Post, Hero Block, etc.)
- [x] Step-by-step guide to add or edit Resources
- [ ] Visual identity guidelines (color palette, font, sources for icons/illustrations)
- [ ] anything else?

**Comment by koudyk** [comment]
These are great points!

Do you think some of these would be better in a CONTRIBUTING.md doc?

**Comment by GabrielPelletier** [comment]
Not sure. To me, it feels like a CONTRIBUTING doc would be more oriented to people that are not the OSOH core team (in charge of updating the website and such), a bit like the Get Involved page of the web site. At least that's how I usually see it used when I land on new repos.

The more I think of it, the more I feel like it can go all in the README. This repo is the website repo, so it makes sense that the README contains instructions on how to edit and work on the website. Plus, most of the listed points are already in the README, or partially. It might get a little long, but as long as it's well organized it should be fine?
